
-- Add Form 49A fields to applications table
ALTER TABLE public.applications
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS first_name text,
  ADD COLUMN IF NOT EXISTS middle_name text,
  ADD COLUMN IF NOT EXISTS last_name text,
  ADD COLUMN IF NOT EXISTS pan_print_name text,
  ADD COLUMN IF NOT EXISTS has_other_name boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS other_name_title text,
  ADD COLUMN IF NOT EXISTS other_last_name text,
  ADD COLUMN IF NOT EXISTS other_first_name text,
  ADD COLUMN IF NOT EXISTS other_middle_name text,
  ADD COLUMN IF NOT EXISTS mother_last_name text,
  ADD COLUMN IF NOT EXISTS mother_first_name text,
  ADD COLUMN IF NOT EXISTS mother_middle_name text,
  ADD COLUMN IF NOT EXISTS is_single_parent boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS parent_on_card text DEFAULT 'father',
  ADD COLUMN IF NOT EXISTS flat_door_block text,
  ADD COLUMN IF NOT EXISTS premises_building text,
  ADD COLUMN IF NOT EXISTS road_street_lane text,
  ADD COLUMN IF NOT EXISTS area_locality text,
  ADD COLUMN IF NOT EXISTS office_name text,
  ADD COLUMN IF NOT EXISTS office_flat text,
  ADD COLUMN IF NOT EXISTS office_premises text,
  ADD COLUMN IF NOT EXISTS office_road text,
  ADD COLUMN IF NOT EXISTS office_area text,
  ADD COLUMN IF NOT EXISTS office_city text,
  ADD COLUMN IF NOT EXISTS office_state text,
  ADD COLUMN IF NOT EXISTS office_pincode text,
  ADD COLUMN IF NOT EXISTS office_country text,
  ADD COLUMN IF NOT EXISTS communication_address text DEFAULT 'residence',
  ADD COLUMN IF NOT EXISTS country_code text DEFAULT '+91',
  ADD COLUMN IF NOT EXISTS std_code text,
  ADD COLUMN IF NOT EXISTS applicant_status text DEFAULT 'individual',
  ADD COLUMN IF NOT EXISTS aadhaar_enrollment_id text,
  ADD COLUMN IF NOT EXISTS name_as_per_aadhaar text,
  ADD COLUMN IF NOT EXISTS source_of_income text[],
  ADD COLUMN IF NOT EXISTS proof_of_identity text,
  ADD COLUMN IF NOT EXISTS proof_of_address text,
  ADD COLUMN IF NOT EXISTS proof_of_dob text,
  ADD COLUMN IF NOT EXISTS declaration_place text,
  ADD COLUMN IF NOT EXISTS declaration_date text;
